language: julia

os:
  - osx
  - linux

julia:
  - nightly
  - 0.6.2

matrix:
  allow_failures:
    - julia: nightly

before_script:
 - julia -e 'Pkg.add("JLD2"); Pkg.add("SpecialFunctions");'
 - julia -e 'Pkg.add("Interpolations"); Pkg.add("FFTW");'
 # - julia -e 'ENV["PYTHON"]=""; Pkg.build("PyCall"); using PyPlot;'

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.test("FourierFlows",coverage=true)'

after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("FourierFlows")); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("FourierFlows")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'cd(Pkg.dir("FourierFlows")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'

notifications:
  email: true
